#ifndef ESPERT_SANDBOX_ESPCULLMODE_HH
#define ESPERT_SANDBOX_ESPCULLMODE_HH

namespace esp
{
  enum EspCullMode
  {
    ESP_CULL_MODE_NONE               = 0,
    ESP_CULL_MODE_FRONT_BIT          = 0x00000001,
    ESP_CULL_MODE_BACK_BIT           = 0x00000002,
    ESP_CULL_MODE_FRONT_AND_BACK     = 0x00000003,
    ESP_CULL_MODE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
  };
}

#endif // ESPERT_SANDBOX_ESPCULLMODE_HH
