#ifndef ESPERT_SANDBOX_ESPPRIMITIVETOPOLOGY_HH
#define ESPERT_SANDBOX_ESPPRIMITIVETOPOLOGY_HH

namespace esp
{
  enum EspPrimitiveTopology
  {
    ESP_PRIMITIVE_TOPOLOGY_POINT_LIST                    = 0,
    ESP_PRIMITIVE_TOPOLOGY_LINE_LIST                     = 1,
    ESP_PRIMITIVE_TOPOLOGY_LINE_STRIP                    = 2,
    ESP_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST                 = 3,
    ESP_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP                = 4,
    ESP_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN                  = 5,
    ESP_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY      = 6,
    ESP_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY     = 7,
    ESP_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY  = 8,
    ESP_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
    ESP_PRIMITIVE_TOPOLOGY_PATCH_LIST                    = 10,
    ESP_PRIMITIVE_TOPOLOGY_MAX_ENUM                      = 0x7FFFFFFF
  };
}

#endif // ESPERT_SANDBOX_ESPPRIMITIVETOPOLOGY_HH
