#ifndef ESP_CORE_MOUSE_BUTTON_CODE_HH
#define ESP_CORE_MOUSE_BUTTON_CODE_HH

/*
  THIS CODE IS FROM glfw3.h
*/

#define ESP_MOUSE_BUTTON_1      0
#define ESP_MOUSE_BUTTON_2      1
#define ESP_MOUSE_BUTTON_3      2
#define ESP_MOUSE_BUTTON_4      3
#define ESP_MOUSE_BUTTON_5      4
#define ESP_MOUSE_BUTTON_6      5
#define ESP_MOUSE_BUTTON_7      6
#define ESP_MOUSE_BUTTON_8      7
#define ESP_MOUSE_BUTTON_LAST   ESP_MOUSE_BUTTON_8
#define ESP_MOUSE_BUTTON_LEFT   ESP_MOUSE_BUTTON_1
#define ESP_MOUSE_BUTTON_RIGHT  ESP_MOUSE_BUTTON_2
#define ESP_MOUSE_BUTTON_MIDDLE ESP_MOUSE_BUTTON_3

#endif /* ESP_CORE_MOUSE_BUTTON_CODE_HH */
