name: clang-tidy-check

on:
  pull_request:
    branches: ['master']

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.14.0
        id: review
        with:
          build_dir: build
          config_file: ".clang-tidy"
          include: "src/*.[ch],src/*.cc,src/*.hh,tests/*.[ch],tests/*.cc,tests/*.hh"
          exclude: "external/*"
          cmake_command: |
            pip install cmake && \
            cmake --version && \
            git config --global --add safe.directory "$GITHUB_WORKSPACE" && \
            cmake . -B build -D-DVKB_WSI_SELECTION=XLIB \
                             -DCMAKE_EXPORT_COMPILE_COMMANDS=on

      - if: steps.review.outputs.total_comments > 0
        run: exit 1