name: clang-tidy-check

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set base_dir
      run: echo "base_dir=$(pwd)" >> $GITHUB_ENV

    - uses: ZedThree/clang-tidy-review@v0.12.0
      id: review
      with:
        cmake_command: cmake . -D-DVKB_WSI_SELECTION=XLIB -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        base_dir: ${{ env.base_dir }}
        include: "src/*.[ch],src/*.cc,src/*.hh,tests/*.[ch],tests/*.cc,tests/*.hh"
        exclude: "external/*"

    - if: steps.review.outputs.total_comments > 0
      run: exit 1