name: clang-tidy-check

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ZedThree/clang-tidy-review@v0.12.0
      id: review
      with:
        cmake_command: cmake . -D-DVKB_WSI_SELECTION=XLIB -DCMAKE_EXPORT_COMPILE_COMMANDS=on

    - if: steps.review.outputs.total_comments > 0
      run: exit 1