name: clang-tidy-check

on:
  pull_request:
    branches: ['master']

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use CMake 3.20.1
        uses: lukka/get-cmake@v3.20.1

      - name: Generate compile_commands.json
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
          # has to be the github workspace, not the runner workspace, for the docker-based clang-tidy-review
          buildDirectory: '${{github.workspace}}/build'
          cmakeAppendedArgs: >-
            -D-DVKB_WSI_SELECTION=XLIB
            -DCMAKE_EXPORT_COMPILE_COMMANDS=on

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.14.0
        id: review
        with:
          build_dir: build
          config_file: ".clang-tidy"
          include: "src/*.[ch],src/*.cc,src/*.hh,tests/*.[ch],tests/*.cc,tests/*.hh"
          exclude: "external/*"

      - if: steps.review.outputs.total_comments > 0
        run: exit 1